name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/mariappan/gh_action:latest

      - name: Adding markdown
        run: |
          echo '### Docker image' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo 'ImageId: ${IMAGE_ID}' >> $GITHUB_STEP_SUMMARY
          echo 'Digest: ${DIGEST}' >> $GITHUB_STEP_SUMMARY
          echo 'Metadata: ${METADATA}' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
        env:
          IMAGE_ID: ${{ steps.build.outputs.image_id }}
          DIGEST: ${{ steps.build.outputs.digest }}
          METADATA: ${{ steps. build.output.metadata }}
